# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
#     includeRootFolder: false

- task: PublishBuildArtifacts@1

#- task: AzureWebApp@1
#  inputs:
#    azureSubscription: 'Microsoft Azure Internal Consumption (153bf828-3e1e-48f9-8e6d-7f69c8e188aa)'
#    appType: 'webApp'
#    appName: 'nodejsapp5601'
#    package: '$(System.DefaultWorkingDirectory)'
#    customWebConfig: '-Handler iisnode -NodeStartFile server.js -appType node'
#    deploymentMethod: 'zipDeploy'

- task: CopyFiles@2
  inputs:
    SourceFolder: '**'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'PublishProfile'
#     PublishProfilePath: '$(System.DefaultWorkingDirectory)/**/*.pubxml'
#     PublishProfilePassword: 'FZw3XxsuTWhEJ1zndzpBeCbR7r8QEn6Qfolddswz6Jr4iNaP5KbeSYobD0CN'
#     packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'